export const FIELD_META_DATA = 'FIELD_META_DATA';
export const REQUIRED_META_DATA = 'REQUIRED_META_DATA';
export const TYPE_META_DATA = 'TYPE_META_DATA';
export const CLASS_TYPE_META_DATA = 'CLASS_TYPE_META_DATA';
export const BUILDER_TYPE_META_DATA = 'BUILDER_TYPE_META_DATA';
export const DEFAULT_VALUE_META_DATA = 'DEFAULT_VALUE_META_DATA';
