export const FIELD_META_DATA = Symbol('FIELD_META_DATA');
export const REQUIRED_META_DATA = Symbol('REQUIRED_META_DATA');
export const TYPE_META_DATA = Symbol('TYPE_META_DATA');
export const CLASS_TYPE_META_DATA = Symbol('CLASS_TYPE_META_DATA');
export const BUILDER_TYPE_META_DATA = Symbol('BUILDER_TYPE_META_DATA');
export const DEFAULT_VALUE_META_DATA = Symbol('DEFAULT_VALUE_META_DATA');
