name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@serglenkov'

      - name: Build library
        run: npm run build

      - name: Test library
        run: npm run test

      - name: Publish
        run: npm run pack-and-publish

      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}